version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  test:
    executor: 
      name: node/default
      tag: '14.17'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: 
          command: yarn run test
      - run: 
          command: yarn run coverage
      - store_artifacts:
          path: test-reports
      - store_test_results:
          path: test-results    
workflows:
  test_my_app:
    jobs:
      - test

