"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "marca",
      [
        {
          IdMarca: 1,
          marca: "Sin marca",
          referencia: "000-000",
          categoria: "A",
          tipo: "Moto",
          descripcion: "Sin categoria",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 2,
          marca: "HONDA",
          referencia: "AFRICA TWIN",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 3,
          marca: "SUZUKI",
          referencia: "BANDIT650",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 4,
          marca: "MV AGUSTA",
          referencia: "BRUTALE 800",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 5,
          marca: "HONDA",
          referencia: "CB1000R",
          categoria: "B",
          tipo: "NAKED",
          descripcion: "BN",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 6,
          marca: "HONDA",
          referencia: "CBR1000RR",
          categoria: "B",
          tipo: "CARENADA",
          descripcion: "BC",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 7,
          marca: "HONDA",
          referencia: "CBR250R",
          categoria: "A-",
          tipo: "",
          descripcion: "A-",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 8,
          marca: "HONDA",
          referencia: "CBR250R ABS",
          categoria: "A-",
          tipo: "",
          descripcion: "A-",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 9,
          marca: "HONDA",
          referencia: "CBR500F",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 10,
          marca: "HONDA",
          referencia: "CBR500X",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 11,
          marca: "HONDA",
          referencia: "CBR600RR",
          categoria: "B",
          tipo: "CARENADA",
          descripcion: "BC",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 12,
          marca: "HONDA",
          referencia: "CRF450R",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 13,
          marca: "TRIUMPH",
          referencia: "DAYTONA 675",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 14,
          marca: "DUCATI",
          referencia: "DIAVEL 1200",
          categoria: "D",
          tipo: "",
          descripcion: "D",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 15,
          marca: "DUCATI",
          referencia: "DIAVEL TITANIUM",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 16,
          marca: "MV AGUSTA",
          referencia: "DRAGSTER",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 17,
          marca: "SUZUKI",
          referencia: "DRZ400SM",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 18,
          marca: "KAWASAKI",
          referencia: "ER6F",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 19,
          marca: "KAWASAKI",
          referencia: "ER6N",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 20,
          marca: "TRIUMPH",
          referencia: "EXPLORER 1200",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 21,
          marca: "MV AGUSTA",
          referencia: "F3 675",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 22,
          marca: "MV AGUSTA",
          referencia: "F3 800 ",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 23,
          marca: "MV AGUSTA",
          referencia: "F4 1000",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 24,
          marca: "BMW",
          referencia: "F650GS",
          categoria: "B",
          tipo: "",
          descripcion: "B",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 25,
          marca: "BMW",
          referencia: "F700GS",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 26,
          marca: "BMW",
          referencia: "F800R-GS",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 27,
          marca: "YAMAHA",
          referencia: "FZ1",
          categoria: "B",
          tipo: "NAKED",
          descripcion: "BN",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 28,
          marca: "YAMAHA",
          referencia: "FZ250",
          categoria: "A-",
          tipo: "",
          descripcion: "A-",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 29,
          marca: "YAMAHA",
          referencia: "FZ6 S1",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 30,
          marca: "YAMAHA",
          referencia: "FZ6 S2",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 31,
          marca: "YAMAHA",
          referencia: "FZ8",
          categoria: "B",
          tipo: "NAKED",
          descripcion: "BN",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 32,
          marca: "BMW",
          referencia: "G650GS",
          categoria: "B",
          tipo: "",
          descripcion: "B",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 33,
          marca: "SUZUKI",
          referencia: "GS500",
          categoria: "",
          tipo: "",
          descripcion: "",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 34,
          marca: "SUZUKI",
          referencia: "GS500E",
          categoria: "",
          tipo: "",
          descripcion: "",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 35,
          marca: "SUZUKI",
          referencia: "GSR600",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 36,
          marca: "SUZUKI",
          referencia: "GSR750",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 37,
          marca: "SUZUKI",
          referencia: "GSX1000R",
          categoria: "B",
          tipo: "NAKED",
          descripcion: "BN",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 38,
          marca: "SUZUKI",
          referencia: "GSX650F",
          categoria: "",
          tipo: "",
          descripcion: "",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 39,
          marca: "SUZUKI",
          referencia: "GSXR1000",
          categoria: "B",
          tipo: "CARENADA",
          descripcion: "BC",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 40,
          marca: "SUZUKI",
          referencia: "GSXR600",
          categoria: "B",
          tipo: "CARENADA",
          descripcion: "BC",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 41,
          marca: "SUZUKI",
          referencia: "GSXR750",
          categoria: "B",
          tipo: "CARENADA",
          descripcion: "BC",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 42,
          marca: "SUZUKI",
          referencia: "GSXS750",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 43,
          marca: "KAWASAKI",
          referencia: "H2",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 44,
          marca: "KAWASAKI",
          referencia: "H2R",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 45,
          marca: "HONDA",
          referencia: "HORNET 600",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 46,
          marca: "BMW",
          referencia: "HP4",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 47,
          marca: "DUCATI",
          referencia: "HYPERESTRADA 800",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 48,
          marca: "DUCATI",
          referencia: "HYPERESTRADA 939",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 49,
          marca: "DUCATI",
          referencia: "HYPERMOTARD 1100",
          categoria: "B",
          tipo: "",
          descripcion: "B",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 50,
          marca: "DUCATI",
          referencia: "HYPERMOTARD 821",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 51,
          marca: "DUCATI",
          referencia: "HYPERMOTARD 939",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 52,
          marca: "SUZUKI",
          referencia: "INAZUMA250",
          categoria: "A-",
          tipo: "",
          descripcion: "A-",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 53,
          marca: "BMW",
          referencia: "K1300R",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 54,
          marca: "BMW",
          referencia: "K1600GT",
          categoria: "D",
          tipo: "",
          descripcion: "D",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 55,
          marca: "KAWASAKI",
          referencia: "KLX 150",
          categoria: "A--",
          tipo: "",
          descripcion: "A--",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 56,
          marca: "KAWASAKI",
          referencia: "KLX 250",
          categoria: "A-",
          tipo: "",
          descripcion: "A-",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 57,
          marca: "DUCATI",
          referencia: "MONSTER 1000",
          categoria: "B",
          tipo: "",
          descripcion: "B",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 58,
          marca: "DUCATI",
          referencia: "MONSTER 1100",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 59,
          marca: "DUCATI",
          referencia: "MONSTER 1200 ",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 60,
          marca: "DUCATI",
          referencia: "MONSTER 795",
          categoria: "B",
          tipo: "",
          descripcion: "B",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 61,
          marca: "DUCATI",
          referencia: "MONSTER 796",
          categoria: "B",
          tipo: "",
          descripcion: "B",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 62,
          marca: "DUCATI",
          referencia: "MONSTER 821",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 63,
          marca: "DUCATI",
          referencia: "MONSTER 996 S4R",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 64,
          marca: "YAMAHA",
          referencia: "MT03",
          categoria: "A-",
          tipo: "",
          descripcion: "A-",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 65,
          marca: "YAMAHA",
          referencia: "MT07",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 66,
          marca: "YAMAHA",
          referencia: "MT09",
          categoria: "B",
          tipo: "NAKED",
          descripcion: "BN",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 67,
          marca: "YAMAHA",
          referencia: "MT10",
          categoria: "B",
          tipo: "NAKED",
          descripcion: "BN",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 68,
          marca: "DUCATI",
          referencia: "MTS 1000",
          categoria: "B",
          tipo: "",
          descripcion: "B",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 69,
          marca: "DUCATI",
          referencia: "MTS 1000 DS",
          categoria: "B",
          tipo: "",
          descripcion: "B",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 70,
          marca: "DUCATI",
          referencia: "MTS 1100",
          categoria: "B",
          tipo: "",
          descripcion: "B",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 71,
          marca: "DUCATI",
          referencia: "MTS 1200",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 72,
          marca: "HONDA",
          referencia: "NC750X",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 73,
          marca: "KAWASAKI",
          referencia: "NINJA250",
          categoria: "A-",
          tipo: "",
          descripcion: "A-",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 74,
          marca: "KAWASAKI",
          referencia: "NINJA300",
          categoria: "A-",
          tipo: "",
          descripcion: "A-",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 75,
          marca: "DUCATI",
          referencia: "PANIGALE 1199",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 76,
          marca: "DUCATI",
          referencia: "PANIGALE 1299 ",
          categoria: "D",
          tipo: "",
          descripcion: "D",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 77,
          marca: "DUCATI",
          referencia: "PANIGALE 899",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 78,
          marca: "DUCATI",
          referencia: "PANIGALE 959",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 79,
          marca: "DUCATI",
          referencia: "PANIGALE V4",
          categoria: "D",
          tipo: "",
          descripcion: "D",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 80,
          marca: "POR REVISAR",
          referencia: "POR REVISAR",
          categoria: "",
          tipo: "",
          descripcion: "",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 81,
          marca: "YAMAHA",
          referencia: "R1",
          categoria: "B",
          tipo: "CARENADA",
          descripcion: "BC",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 82,
          marca: "BMW",
          referencia: "R1200GS K25",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 83,
          marca: "BMW",
          referencia: "R1200GS K50",
          categoria: "D",
          tipo: "",
          descripcion: "D",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 84,
          marca: "BMW",
          referencia: "R1200GS K51",
          categoria: "D",
          tipo: "",
          descripcion: "D",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 85,
          marca: "YAMAHA",
          referencia: "R15",
          categoria: "A--",
          tipo: "",
          descripcion: "A--",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 86,
          marca: "YAMAHA",
          referencia: "R3",
          categoria: "A-",
          tipo: "",
          descripcion: "A-",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 87,
          marca: "YAMAHA",
          referencia: "R6R",
          categoria: "B",
          tipo: "CARENADA",
          descripcion: "BC",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 88,
          marca: "YAMAHA",
          referencia: "R6S",
          categoria: "B",
          tipo: "CARENADA",
          descripcion: "BC",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 89,
          marca: "SUZUKI",
          referencia: "RMZ450",
          categoria: "",
          tipo: "",
          descripcion: "",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 90,
          marca: "BMW",
          referencia: "S1000R ",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 91,
          marca: "BMW",
          referencia: "S1000RR",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 92,
          marca: "BMW",
          referencia: "S1000XR",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 93,
          marca: "DUCATI",
          referencia: "SCRAMBLER 400",
          categoria: "B",
          tipo: "",
          descripcion: "B",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 94,
          marca: "DUCATI",
          referencia: "SCRAMBLER 800",
          categoria: "B",
          tipo: "",
          descripcion: "B",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 95,
          marca: "TRIUMPH",
          referencia: "STREET TRIPLE 675",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 96,
          marca: "DUCATI",
          referencia: "STREETFIGHTER 848",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 97,
          marca: "YAMAHA",
          referencia: "SUPERTENERE 1200",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 98,
          marca: "SUZUKI",
          referencia: "SV650",
          categoria: "",
          tipo: "",
          descripcion: "",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 99,
          marca: "YAMAHA",
          referencia: "TDM900",
          categoria: "B",
          tipo: "TOURING",
          descripcion: "BT",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 100,
          marca: "YAMAHA",
          referencia: "TENERE 660",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 101,
          marca: "TRIUMPH",
          referencia: "TIGER 800 XRX",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 102,
          marca: "YAMAHA",
          referencia: "TRACER",
          categoria: "B",
          tipo: "TOURING",
          descripcion: "BT",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 103,
          marca: "UNIVERSAL",
          referencia: "UNIVERSAL",
          categoria: "",
          tipo: "",
          descripcion: "",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 104,
          marca: "KAWASAKI",
          referencia: "VERSYS 1000",
          categoria: "B",
          tipo: "TOURING",
          descripcion: "BT",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 105,
          marca: "KAWASAKI",
          referencia: "VERSYS 250",
          categoria: "A-",
          tipo: "",
          descripcion: "A-",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 106,
          marca: "KAWASAKI",
          referencia: "VERSYS 650",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 107,
          marca: "HONDA",
          referencia: "VFR1200X",
          categoria: "C",
          tipo: "",
          descripcion: "C",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 108,
          marca: "HONDA",
          referencia: "VFR800X",
          categoria: "B",
          tipo: "TOURING",
          descripcion: "BT",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 109,
          marca: "SUZUKI",
          referencia: "VSTROM1000",
          categoria: "B",
          tipo: "TOURING",
          descripcion: "BT",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 110,
          marca: "SUZUKI",
          referencia: "VSTROM250",
          categoria: "A-",
          tipo: "",
          descripcion: "A-",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 111,
          marca: "SUZUKI",
          referencia: "VSTROM650",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 112,
          marca: "YAMAHA",
          referencia: "WR250R",
          categoria: "",
          tipo: "",
          descripcion: "",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 113,
          marca: "DUCATI",
          referencia: "XDIAVEL",
          categoria: "D",
          tipo: "",
          descripcion: "D",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 114,
          marca: "YAMAHA",
          referencia: "XJ6F",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 115,
          marca: "YAMAHA",
          referencia: "XJ6N",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 116,
          marca: "HONDA",
          referencia: "XRE 300",
          categoria: "A-",
          tipo: "",
          descripcion: "A-",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 117,
          marca: "YAMAHA",
          referencia: "XT1200Z",
          categoria: "B",
          tipo: "TOURING",
          descripcion: "BT",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 118,
          marca: "YAMAHA",
          referencia: "XT660",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 119,
          marca: "YAMAHA",
          referencia: "YZ450",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 120,
          marca: "KAWASAKI",
          referencia: "Z1000",
          categoria: "B",
          tipo: "NAKED",
          descripcion: "BN",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 121,
          marca: "KAWASAKI",
          referencia: "Z250",
          categoria: "A-",
          tipo: "",
          descripcion: "A-",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 122,
          marca: "KAWASAKI",
          referencia: "Z250SL",
          categoria: "A-",
          tipo: "",
          descripcion: "A-",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 123,
          marca: "KAWASAKI",
          referencia: "Z650",
          categoria: "A",
          tipo: "",
          descripcion: "A",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 124,
          marca: "KAWASAKI",
          referencia: "Z800",
          categoria: "B",
          tipo: "NAKED",
          descripcion: "BN",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 125,
          marca: "KAWASAKI",
          referencia: "Z900",
          categoria: "B",
          tipo: "NAKED",
          descripcion: "BN",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 126,
          marca: "KAWASAKI",
          referencia: "ZX10R",
          categoria: "B",
          tipo: "CARENADA",
          descripcion: "BC",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 127,
          marca: "KAWASAKI",
          referencia: "ZX636R",
          categoria: "B",
          tipo: "CARENADA",
          descripcion: "BC",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
        {
          IdMarca: 128,
          marca: "KAWASAKI",
          referencia: "ZX6R (2006 - 2012)",
          categoria: "B",
          tipo: "CARENADA",
          descripcion: "BC",
          tipoVehiculo: "Moto",
          urllogo: "https://branchweb.herokuapp.com/assets/img/logo-branch.svg",
        },
      ],
      {}
    );
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkDelete('People', null, {});
    */
    return queryInterface.bulkDelete("marca", null, {});
  },
};
